module.exports = {
  CHANNELS_RECEIVED: "CHANNELS_RECEIVED",
  SUBSCRIBED_CHANNEL_RECEIVED: "SUBSCRIBED_CHANNEL_RECEIVED",
  SET_CURRENT_CHANNEL: "SET_CURRENT_CHANNEL",
  LEAVE_CHANNEL: "LEAVE_CHANNEL",
  TOGGLE_SUBSCRIPTION: "TOGGLE_SUBSCRIPTION"
};
